---
sidebar: sidebar
permalink: task-administer-storagegrid.html
keywords: grid manager, advanced view, standard view, use grid manager, gridmanager
summary: Administer a StorageGRID system from the NetApp Console by using the advanced view. This view enables you to use Grid Manager from within the NetApp Console.
---

= Administer StorageGRID using the Grid Manager in the NetApp Console
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Administer a StorageGRID system from the Console by using the advanced view. This view enables you to use Grid Manager from the Console.

.Required NetApp Console role:
Storage admin, or System health specialist. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about access roles^].

== Supported configurations

Grid Manager is available in the Console starting with StorageGRID 11.8.

== Limitations

The following Grid Manager operations are not available from the Console. If you need to perform these operations, sign in to the Grid Manager directly.

[cols="1a,2a" options=header] 
|===
| Grid Manager menu
| Operations not available from the Console

| User
| 
* Sign out link
* API documentation link
* Change password

| Nodes
| 
* You can't access SANtricity System Manager from the Nodes > SANtricity System Manager tab. 
* When viewing alerts, you might not be able to select all links in the recommended actions. For example, links that go to unsupported Grid Manager pages will not work.

| Tenants
| You can't sign in to a tenant account from the Create a tenant wizard or from the Tenants page.

The Console doesn't currently support the Tenant Manager. Although you can create new tenant accounts from the Console, tenant users can't sign into their accounts from the Console.

| ILM
| Storage grades link

| Configuration
| 
* Grid passwords
* Security settings > Browser inactivity timeout
* Single sign-on 
* SNMP agent > MIB file for BMC interface

| Maintenance

| 
* Recovery Package
* Software update

| Support

| 
* Grid topology
* Log collection
* All links to Prometheus metrics and Grafana dashboards
* All options for legacy alarms
* Link cost
* NMS entities
|===

== Switch to Grid Manager

Open a StorageGRID system and select the Grid Manager option.

.Steps

. From the *Systems* page, open the StorageGRID system.

. In the top-right, select *Switch to Grid Manager*.

. Use Grid Manager to manage the StorageGRID system.

. If needed, select *Go back* to return to standard view through Console.

== Get help with Grid Manager

If you need help using Grid Manager, refer to https://docs.netapp.com/us-en/storagegrid/admin/index.html[StorageGRID documentation^] for step-by-step instructions.